### ISSUE TITLE
Some comments are wrong

### ISSUE THREAD

**Issue by paternal** [nixjdm/lektor-tags#10]
Hello,
some of the comments are specific to your website, but they should be more generic:

https://github.com/ajdavis/lektor-tags/blob/72cf4e9eef140f8c7ce4e092ce531792398f8993/lektor_tags.py#L65-L66

(I stumbled upon this as I am trying to learn how to write Lektor plugins by reading your code.)

-- Louis

**Comment by nixjdm** [comment]
I've fixed this. Thanks!
